# Generated by Django 4.0.2 on 2022-03-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_by',
            new_name='host',
        ),
    ]
