# Generated by Django 4.0.2 on 2022-03-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_user_gender_alter_message_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
    ]
