# Generated by Django 4.0.2 on 2022-03-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_room_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
